_setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat_app.urls')),
]

chat_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path('', views.home, name='home'),
        path('conversation/<int:pk>/', views.conversation_detail, name='conversation_detail'),
        path('conversation_search/<title>/', views.conversation_search_results, name='conversation_search_results'),
        path('message_search/<search_text>/', views.message_search_results, name='message_search_results'),
]

chat_app/models.py
from django.db import models
from datetime import date


class Conversation(models.Model):
    title = models.CharField(max_length=255)
    start_date = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.title}"


class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    text = models.TextField()
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message: {self.text}"


class MessageThought(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    text = models.TextField()
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Thought: {self.text}"

chat_app/forms.py
from django import forms
from .models import Conversation, Message, MessageThought


class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['title']
        widgets = {'title': forms.TextInput(attrs={
            'placeholder': 'New conversation',
            'maxlength': Conversation._meta.get_field('title').max_length})
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'Send a new message'})}


class MessageThoughtForm(forms.ModelForm):
    class Meta:
        model = MessageThought
        fields = ['text', 'message']
        widgets = {
            'text': forms.TextInput(attrs={'placeholder': 'Add your thoughts'}),
            'message': forms.HiddenInput(attrs={'type': 'hidden'})
            }


class ConversationSearchForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['title']
        widgets = {'title': forms.TextInput(attrs={
            'placeholder': 'Search for conversation by title',
            'maxlength': Conversation._meta.get_field('title').max_length})
        }


class MessageSearchForm(forms.ModelForm):
    # max length matches the max length of the title
    class Meta:
        model = Message
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'Search for message by content'})}

chat_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core import serializers
from .models import Conversation, Message, MessageThought
from .forms import ConversationForm, MessageForm, MessageThoughtForm, ConversationSearchForm, MessageSearchForm


def home(request):
    if 'search_context' in request.session:
        del request.session['search_context']

    conversations = Conversation.objects.all()
    conversation_form = ConversationForm()
    conversation_search_form = ConversationSearchForm()
    message_search_form = MessageSearchForm()

    if request.method == 'POST':
        if 'conversation_form_submit' in request.POST:
            conversation_form = ConversationForm(request.POST)
            if conversation_form.is_valid():
                conversation = conversation_form.save()
                return redirect('conversation_detail', pk=conversation.pk)

    if request.method == 'GET':
        if 'conversation_search_form_submit' in request.GET:
            conversation_search_form = ConversationSearchForm(request.GET)  # Pass request.GET data to the form
            if conversation_search_form.is_valid():
                print("GET REQUEST")
                title = conversation_search_form.cleaned_data.get('title')
                filtered_conversations = conversations.filter(title__icontains=title)
                print(list(filtered_conversations))
                context = {
                    'title': title,
                    'filtered_conversations': list(filtered_conversations.values_list('pk', flat=True)),
                }
                request.session['search_context'] = context
                return redirect('conversation_search_results', title)
        if 'message_search_form_submit' in request.GET:
            message_search_form = MessageSearchForm(request.GET)  # Pass request.GET data to the form
            if message_search_form.is_valid():
                messages = Message.objects.all()
                print("GET REQUEST")
                search_text = message_search_form.cleaned_data.get('text')
                filtered_messages = messages.filter(text__icontains=search_text)
                print(list(filtered_messages))
                context = {
                    'search_text': search_text,
                    'filtered_messages': list(filtered_messages.values_list('pk', flat=True)),
                }
                request.session['search_context'] = context
                return redirect('message_search_results', search_text)


    else:
        conversation_form = ConversationForm()
        conversation_search_form = ConversationSearchForm()
        message_search_form = MessageSearchForm()

    context = {
        'conversations': conversations,
        'conversation_form': conversation_form,
        'conversation_search_form': conversation_search_form,
        'message_search_form': message_search_form,
    }
    return render(request, 'home.html', context)

def conversation_detail(request, pk):
    if 'search_context' in request.session:
        del request.session['search_context']

    conversation = get_object_or_404(Conversation, pk=pk)
    messages = conversation.message_set.all()
    message_form = MessageForm()
    thought_form = MessageThoughtForm()
    conversation_form = ConversationForm()

    if request.method == 'POST':
        if 'message_form_submit' in request.POST:
            message_form = MessageForm(request.POST)
            if message_form.is_valid():
                message = message_form.save(commit=False)
                message.conversation = conversation
                message.save()
                return redirect('conversation_detail', pk=conversation.pk)
        if 'thought_form_submit' in request.POST:
            thought_form = MessageThoughtForm(request.POST)
            if thought_form.is_valid():
                message_id = request.POST['message']
                message = Message.objects.get(id=message_id)
                thought = thought_form.save(commit=False)
                thought.message = message
                thought.save()
                return redirect('conversation_detail', pk=message.conversation.pk)
        if 'conversation_form_submit' in request.POST:
            new_conversation_form = ConversationForm(request.POST)
            if new_conversation_form.is_valid():
                conversation = new_conversation_form.save()
                return redirect('conversation_detail', pk=conversation.pk)
    else:
        message_form = MessageForm()
        thought_form = MessageThoughtForm()
        conversation_form = ConversationForm()

    conversations = Conversation.objects.all()

    context = {
        'conversation': conversation,
        'messages': messages,
        'message_form': message_form,
        'thought_form': thought_form,
        'conversation_form': conversation_form,
        'conversations': conversations,
    }

    return render(request, 'chat_app/conversation_detail.html', context)


def conversation_search_results(request, title):
    conversations = Conversation.objects.all()

    #context contains search title and a list of conversation pks
    context = request.session['search_context']
    conversation_ids = context['filtered_conversations']
    filtered_conversations = Conversation.objects.filter(id__in=conversation_ids)
    context['filtered_conversations'] = filtered_conversations
    context['conversations'] = conversations

    return render(request, 'chat_app/conversation_search_results.html', context)

def message_search_results(request, search_text):
    conversations = Conversation.objects.all()

    #context contains search text and a list of message pks
    context = request.session['search_context']
    message_ids = context['filtered_messages']
    filtered_messages = Message.objects.filter(id__in=message_ids)
    context['filtered_messages'] = filtered_messages
    context['conversations'] = conversations

    return render(request, 'chat_app/message_search_results.html', context)

chat_app/templates/chat_app/conversation_detail.html
{% extends 'index.html' %}


{% block content %}
<h1>{{ conversation.title }}</h1>
<body>Started: {{ conversation.start_date|date:"F d" }}</body>

<ul class="message-list">
  {% for message in messages %}
    <li class="message-item">
      <div class="message-content">{{ message.text }}</div>
      <div class="message-timestamp">{{ message.date_sent|date:"F d, Y H:i" }}</div>
      <ul class="thought-list">
        {% for thought in message.messagethought_set.all %}
          <li class="thought-item">
            <div class="thought-content">{{ thought.text }}</div>
            <div class="thought-timestamp">{{ thought.date_sent|date:"F d, Y H:i" }}</div>
          </li>
        {% endfor %}
        <div class="new-thought-form">
          <form method="post">
            {% csrf_token %}
            {{ thought_form.text }}
            <input type="hidden" name="message" value="{{ message.id }}">
            <button type="submit" class="thought-form-submit" name="thought_form_submit">Send Thought</button>
          </form>
        </div>
      </ul>
    </li>
  {% endfor %}
</ul>

<div class="new-message-form">
  <form method="post">
    {% csrf_token %}
      {{ message_form.text }}
    <button type="submit" class="message-form-submit" name="message_form_submit">Send Message</button>
  </form>
</div>
{% endblock %}

chat_app/templates/chat_app/conversation_search_results.html
{% extends 'index.html' %}


{% block content %}

    <h1>Search results for conversations titled: "{{ title }}"</h1>
    <ul class="conversations">
        {% for conversation in filtered_conversations %}
          <li class="conversation-list-item">
              <a href="{% url 'conversation_detail' conversation.id %}">{{ conversation.title }}</a>
          </li>
        {% endfor %}
    </ul>

{% endblock %}

chat_app/templates/chat_app/message_search_results.html
{% extends 'index.html' %}


{% block content %}

    <h1>Search results for messages with content: "{{ search_text }}"</h1>
    <ul class="message-list">
        {% for message in filtered_messages %}
          <a href="{% url 'conversation_detail' message.conversation_id %}">{{ message.conversation.title }}</a>
          <li class="message-item">
              <div class="message-content">{{ message.text }}</div>
              <div class="message-timestamp">{{ message.date_sent|date:"F d, Y H:i" }}</div>
              <ul class="thought-list">
                {% for thought in message.messagethought_set.all %}
                  <li class="thought-item">
                    <div class="thought-content">{{ thought.text }}</div>
                    <div class="thought-timestamp">{{ thought.date_sent|date:"F d, Y H:i" }}</div>
                  </li>
                {% endfor %}
              </ul>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

chat_app/templates/home.html
{% extends 'index.html' %}

{% block content %}
  <h1>Select a chat to the left, search below, or start a new conversation</h1>
  <br><br><br>
  <form method="get" class="new-conversation-form">
    {% csrf_token %}
      {{ conversation_search_form.as_p }}
    <button type="submit" class="conversation-form-submit" name="conversation_search_form_submit">Search conversations</button>
  </form>
  <br><br><br><br>
  <form method="get" class="new-conversation-form">
    {% csrf_token %}
      {{ message_search_form.as_p }}
    <button type="submit" class="conversation-form-submit" name="message_search_form_submit">Search messages</button>
  </form>

{% endblock %}

chat_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

{% block title %}<title>Chat App</title>{% endblock %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/custom_styles.css' %}">

<body>
    <div id="sidebar">
        <ul>
            {% block sidebar %}
            <ul class="conversations">
              <li class="conversation-list-item"><a href="{% url 'home' %}">Home / Search </a></li>
                <li class="conversation-list-item">Conversations</li>
                {% for conversation in conversations %}
                    <li class="conversation-list-item">
                        <a href="{% url 'conversation_detail' conversation.id %}">{{ conversation.title }}</a>
                    </li>
                {% endfor %}
                <li class="conversation-list-item">
                  <form method="post" class="new-conversation-form">
                    {% csrf_token %}
                    {{ conversation_form.as_p }}
                    <button type="submit" class="conversation-form-submit" name="conversation_form_submit">Create Conversation</button>
                  </form>
                </li>
            </ul>
            {% endblock %}
        </ul>
      </div>
      <div id="content">
          {% block content %}
          {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>